/*
  # Fix Missing Project Data

  1. New Data
     - Add remaining PHP projects (101-200) to complete 200 projects
     - Add all HTML & CSS projects (1-200) 
     - Add all React projects (1-200)

  2. Data Structure
     - Each project has: id, title, description, stage, stage_name, difficulty, project_type
     - PHP: stages 1-4 (Logika & Dasar PHP, Formulir & Validasi, CRUD & Database, Mini Web App)
     - HTML & CSS: stages 1-4 (Dasar, Menengah, Lanjutan, Mahir)
     - React: stages 1-4 (Komponen, Props & State Dasar, State Lanjutan & Event Handling, Routing, Hooks & API, Mini Project & Layout UI)

  3. Security
     - All projects are viewable by authenticated users
*/

-- First, let's clear any existing data to avoid conflicts
DELETE FROM projects WHERE project_type IN ('html-css', 'react') OR (project_type = 'php' AND id > 100);

-- Add remaining PHP projects (101-200)
INSERT INTO projects (id, title, description, stage, stage_name, difficulty, project_type) VALUES
-- Stage 4: Mini Web Applications (101-200)
(101, 'Mini POS', 'Point of Sale system lengkap', 4, 'Mini Web App', 'hard', 'php'),
(102, 'Aplikasi absensi', 'Employee attendance system', 4, 'Mini Web App', 'hard', 'php'),
(103, 'Booking kursi bioskop', 'Cinema seat reservation', 4, 'Mini Web App', 'hard', 'php'),
(104, 'Sistem voting', 'Electronic voting system', 4, 'Mini Web App', 'hard', 'php'),
(105, 'To-do list', 'Task management application', 4, 'Mini Web App', 'medium', 'php'),
(106, 'Pengingat jadwal', 'Schedule reminder system', 4, 'Mini Web App', 'hard', 'php'),
(107, 'Kasir sederhana', 'Simple cashier system', 4, 'Mini Web App', 'hard', 'php'),
(108, 'Galeri foto/video', 'Multimedia gallery with upload', 4, 'Mini Web App', 'hard', 'php'),
(109, 'Lirik lagu', 'Song lyrics database', 4, 'Mini Web App', 'medium', 'php'),
(110, 'Resep masakan', 'Recipe sharing platform', 4, 'Mini Web App', 'hard', 'php'),
(111, 'Review buku', 'Book review system', 4, 'Mini Web App', 'hard', 'php'),
(112, 'Reminder tagihan', 'Bill reminder system', 4, 'Mini Web App', 'hard', 'php'),
(113, 'Sistem rating', 'Rating and review system', 4, 'Mini Web App', 'hard', 'php'),
(114, 'Tracking pesanan', 'Order tracking system', 4, 'Mini Web App', 'hard', 'php'),
(115, 'Penilaian produk', 'Product review platform', 4, 'Mini Web App', 'hard', 'php'),
(116, 'Sistem arsip digital', 'Digital archive system', 4, 'Mini Web App', 'hard', 'php'),
(117, 'Katalog tanaman', 'Plant catalog database', 4, 'Mini Web App', 'medium', 'php'),
(118, 'Aplikasi konsultasi', 'Consultation booking app', 4, 'Mini Web App', 'hard', 'php'),
(119, 'Donasi dan crowdfunding', 'Crowdfunding platform', 4, 'Mini Web App', 'hard', 'php'),
(120, 'Upload multi-file', 'Multiple file upload system', 4, 'Mini Web App', 'hard', 'php'),
(121, 'Aplikasi kurir / cek resi', 'Package tracking system', 4, 'Mini Web App', 'hard', 'php'),
(122, 'Pendaftaran online', 'Online registration system', 4, 'Mini Web App', 'hard', 'php'),
(123, 'Sistem pengajuan cuti', 'Leave request system', 4, 'Mini Web App', 'hard', 'php'),
(124, 'Notifikasi dinamis', 'Dynamic notification system', 4, 'Mini Web App', 'hard', 'php'),
(125, 'Web portofolio', 'Portfolio website builder', 4, 'Mini Web App', 'medium', 'php'),
(126, 'Undangan digital', 'Digital invitation system', 4, 'Mini Web App', 'hard', 'php'),
(127, 'Web profil sekolah', 'School profile website', 4, 'Mini Web App', 'hard', 'php'),
(128, 'Login dengan captcha', 'Secure login with captcha', 4, 'Mini Web App', 'hard', 'php'),
(129, 'Kirim data ke JS', 'PHP to JavaScript data transfer', 4, 'Mini Web App', 'medium', 'php'),
(130, 'Cronjob laporan mingguan', 'Automated weekly reports', 4, 'Mini Web App', 'hard', 'php'),
(131, 'E-commerce mini', 'Mini e-commerce platform', 4, 'Mini Web App', 'hard', 'php'),
(132, 'Chat real-time', 'Real-time chat application', 4, 'Mini Web App', 'hard', 'php'),
(133, 'Blog dengan komentar', 'Blog platform with comments', 4, 'Mini Web App', 'hard', 'php'),
(134, 'Forum diskusi', 'Discussion forum platform', 4, 'Mini Web App', 'hard', 'php'),
(135, 'Booking ruangan', 'Room booking system', 4, 'Mini Web App', 'hard', 'php'),
(136, 'Sistem ujian online', 'Online examination system', 4, 'Mini Web App', 'hard', 'php'),
(137, 'Perpustakaan digital', 'Digital library system', 4, 'Mini Web App', 'hard', 'php'),
(138, 'Sistem antrian', 'Queue management system', 4, 'Mini Web App', 'hard', 'php'),
(139, 'Laporan keuangan', 'Financial reporting system', 4, 'Mini Web App', 'hard', 'php'),
(140, 'Sistem HR', 'Human Resource management', 4, 'Mini Web App', 'hard', 'php'),
(141, 'Manajemen event', 'Event management system', 4, 'Mini Web App', 'hard', 'php'),
(142, 'Sistem parkir', 'Parking management system', 4, 'Mini Web App', 'hard', 'php'),
(143, 'Aplikasi cuaca', 'Weather application with API', 4, 'Mini Web App', 'hard', 'php'),
(144, 'Sistem reservasi', 'General reservation system', 4, 'Mini Web App', 'hard', 'php'),
(145, 'Manajemen proyek', 'Project management tool', 4, 'Mini Web App', 'hard', 'php'),
(146, 'Sistem helpdesk', 'Help desk ticketing system', 4, 'Mini Web App', 'hard', 'php'),
(147, 'Aplikasi fitness', 'Fitness tracking application', 4, 'Mini Web App', 'hard', 'php'),
(148, 'Sistem monitoring', 'System monitoring dashboard', 4, 'Mini Web App', 'hard', 'php'),
(149, 'Aplikasi delivery', 'Food delivery application', 4, 'Mini Web App', 'hard', 'php'),
(150, 'Sistem membership', 'Membership management system', 4, 'Mini Web App', 'hard', 'php'),
(151, 'Aplikasi rental', 'Rental management system', 4, 'Mini Web App', 'hard', 'php'),
(152, 'Sistem survey', 'Survey and polling system', 4, 'Mini Web App', 'hard', 'php'),
(153, 'Aplikasi travel', 'Travel booking platform', 4, 'Mini Web App', 'hard', 'php'),
(154, 'Sistem logistik', 'Logistics management system', 4, 'Mini Web App', 'hard', 'php'),
(155, 'Aplikasi learning', 'Learning management system', 4, 'Mini Web App', 'hard', 'php'),
(156, 'Sistem IoT', 'IoT device management', 4, 'Mini Web App', 'hard', 'php'),
(157, 'Aplikasi streaming', 'Video streaming platform', 4, 'Mini Web App', 'hard', 'php'),
(158, 'Sistem CRM', 'Customer Relationship Management', 4, 'Mini Web App', 'hard', 'php'),
(159, 'Aplikasi marketplace', 'Marketplace platform', 4, 'Mini Web App', 'hard', 'php'),
(160, 'Sistem ERP', 'Enterprise Resource Planning', 4, 'Mini Web App', 'hard', 'php'),
(161, 'Aplikasi banking', 'Banking system simulation', 4, 'Mini Web App', 'hard', 'php'),
(162, 'Sistem blockchain', 'Blockchain implementation', 4, 'Mini Web App', 'hard', 'php'),
(163, 'Aplikasi AI', 'AI-powered application', 4, 'Mini Web App', 'hard', 'php'),
(164, 'Sistem game', 'Web-based game platform', 4, 'Mini Web App', 'hard', 'php'),
(165, 'Aplikasi social media', 'Social media platform', 4, 'Mini Web App', 'hard', 'php'),
(166, 'Sistem automation', 'Workflow automation system', 4, 'Mini Web App', 'hard', 'php'),
(167, 'Aplikasi analytics', 'Analytics dashboard', 4, 'Mini Web App', 'hard', 'php'),
(168, 'Sistem security', 'Security monitoring system', 4, 'Mini Web App', 'hard', 'php'),
(169, 'Aplikasi mobile API', 'Mobile app backend API', 4, 'Mini Web App', 'hard', 'php'),
(170, 'Sistem microservice', 'Microservice architecture', 4, 'Mini Web App', 'hard', 'php'),
(171, 'Aplikasi real-time', 'Real-time data application', 4, 'Mini Web App', 'hard', 'php'),
(172, 'Sistem cloud', 'Cloud-based application', 4, 'Mini Web App', 'hard', 'php'),
(173, 'Aplikasi blockchain', 'Blockchain application', 4, 'Mini Web App', 'hard', 'php'),
(174, 'Sistem machine learning', 'ML-powered system', 4, 'Mini Web App', 'hard', 'php'),
(175, 'Aplikasi VR/AR', 'VR/AR web application', 4, 'Mini Web App', 'hard', 'php'),
(176, 'Sistem big data', 'Big data processing system', 4, 'Mini Web App', 'hard', 'php'),
(177, 'Aplikasi quantum', 'Quantum computing interface', 4, 'Mini Web App', 'hard', 'php'),
(178, 'Sistem neural network', 'Neural network implementation', 4, 'Mini Web App', 'hard', 'php'),
(179, 'Aplikasi cybersecurity', 'Cybersecurity monitoring', 4, 'Mini Web App', 'hard', 'php'),
(180, 'Sistem distributed', 'Distributed system architecture', 4, 'Mini Web App', 'hard', 'php'),
(181, 'Aplikasi edge computing', 'Edge computing platform', 4, 'Mini Web App', 'hard', 'php'),
(182, 'Sistem serverless', 'Serverless architecture', 4, 'Mini Web App', 'hard', 'php'),
(183, 'Aplikasi container', 'Container orchestration', 4, 'Mini Web App', 'hard', 'php'),
(184, 'Sistem kubernetes', 'Kubernetes deployment', 4, 'Mini Web App', 'hard', 'php'),
(185, 'Aplikasi devops', 'DevOps automation platform', 4, 'Mini Web App', 'hard', 'php'),
(186, 'Sistem monitoring', 'Infrastructure monitoring', 4, 'Mini Web App', 'hard', 'php'),
(187, 'Aplikasi testing', 'Automated testing platform', 4, 'Mini Web App', 'hard', 'php'),
(188, 'Sistem deployment', 'Deployment automation', 4, 'Mini Web App', 'hard', 'php'),
(189, 'Aplikasi performance', 'Performance monitoring', 4, 'Mini Web App', 'hard', 'php'),
(190, 'Sistem scalability', 'Auto-scaling system', 4, 'Mini Web App', 'hard', 'php'),
(191, 'Aplikasi load balancer', 'Load balancing system', 4, 'Mini Web App', 'hard', 'php'),
(192, 'Sistem caching', 'Advanced caching system', 4, 'Mini Web App', 'hard', 'php'),
(193, 'Aplikasi CDN', 'Content Delivery Network', 4, 'Mini Web App', 'hard', 'php'),
(194, 'Sistem backup', 'Automated backup system', 4, 'Mini Web App', 'hard', 'php'),
(195, 'Aplikasi disaster recovery', 'Disaster recovery system', 4, 'Mini Web App', 'hard', 'php'),
(196, 'Sistem high availability', 'High availability architecture', 4, 'Mini Web App', 'hard', 'php'),
(197, 'Aplikasi fault tolerance', 'Fault-tolerant system', 4, 'Mini Web App', 'hard', 'php'),
(198, 'Sistem optimization', 'Performance optimization', 4, 'Mini Web App', 'hard', 'php'),
(199, 'Aplikasi enterprise', 'Enterprise-grade system', 4, 'Mini Web App', 'hard', 'php'),
(200, 'Sistem masterpiece', 'Your ultimate PHP masterpiece', 4, 'Mini Web App', 'hard', 'php');

-- Add all HTML & CSS projects (1-200) with new IDs starting from 201
INSERT INTO projects (id, title, description, stage, stage_name, difficulty, project_type) VALUES
-- Stage 1: Dasar (1-50)
(201, 'Halaman Hello World', 'Membuat halaman HTML pertama dengan pesan sederhana', 1, 'Dasar', 'easy', 'html-css'),
(202, 'Biodata pribadi dengan tag HTML', 'Membuat biodata menggunakan berbagai tag HTML dasar', 1, 'Dasar', 'easy', 'html-css'),
(203, 'Daftar belanja menggunakan ul dan li', 'Membuat daftar belanja dengan unordered list', 1, 'Dasar', 'easy', 'html-css'),
(204, 'Form kontak sederhana', 'Membuat form kontak dengan input dasar', 1, 'Dasar', 'easy', 'html-css'),
(205, 'Tombol dengan berbagai warna', 'Styling tombol dengan CSS warna berbeda', 1, 'Dasar', 'easy', 'html-css'),
(206, 'Halaman "About Me"', 'Halaman tentang diri dengan informasi personal', 1, 'Dasar', 'easy', 'html-css'),
(207, 'Layout 1 kolom', 'Membuat layout satu kolom sederhana', 1, 'Dasar', 'easy', 'html-css'),
(208, 'Layout 2 kolom dengan float', 'Layout dua kolom menggunakan CSS float', 1, 'Dasar', 'medium', 'html-css'),
(209, 'Gambar dengan teks deskripsi', 'Menampilkan gambar dengan caption dan deskripsi', 1, 'Dasar', 'easy', 'html-css'),
(210, 'Halaman profil tokoh idola', 'Profil tokoh dengan foto dan informasi lengkap', 1, 'Dasar', 'easy', 'html-css'),
(211, 'Tabel jadwal pelajaran', 'Tabel jadwal dengan styling CSS', 1, 'Dasar', 'medium', 'html-css'),
(212, 'Daftar hobi dengan ikon', 'List hobi dengan icon dan styling menarik', 1, 'Dasar', 'easy', 'html-css'),
(213, 'Halaman ucapan ulang tahun', 'Halaman ucapan dengan desain festif', 1, 'Dasar', 'easy', 'html-css'),
(214, 'Formulir pendaftaran acara', 'Form pendaftaran event dengan berbagai input', 1, 'Dasar', 'medium', 'html-css'),
(215, 'Halaman error 404 statis', 'Custom 404 error page dengan styling', 1, 'Dasar', 'medium', 'html-css'),
(216, 'Header dengan logo dan judul', 'Header section dengan branding', 1, 'Dasar', 'easy', 'html-css'),
(217, 'Footer dengan informasi kontak', 'Footer dengan contact information', 1, 'Dasar', 'easy', 'html-css'),
(218, 'Kotak teks dengan border CSS', 'Text box dengan styling border kreatif', 1, 'Dasar', 'easy', 'html-css'),
(219, 'Paragraf dengan warna dan ukuran berbeda', 'Typography styling dengan variasi warna dan size', 1, 'Dasar', 'easy', 'html-css'),
(220, 'Desain tombol hover', 'Button dengan hover effects menarik', 1, 'Dasar', 'medium', 'html-css'),
(221, 'List menu dengan link', 'Menu navigation dengan link styling', 1, 'Dasar', 'easy', 'html-css'),
(222, 'Tabel data siswa', 'Tabel data dengan styling professional', 1, 'Dasar', 'medium', 'html-css'),
(223, 'Halaman FAQ sederhana', 'FAQ page dengan question dan answer', 1, 'Dasar', 'medium', 'html-css'),
(224, 'Kartu informasi menggunakan div', 'Information card dengan div styling', 1, 'Dasar', 'medium', 'html-css'),
(225, 'Halaman pengumuman', 'Announcement page dengan styling menarik', 1, 'Dasar', 'easy', 'html-css'),
(226, 'Judul dan subjudul dengan heading', 'Typography hierarchy dengan heading tags', 1, 'Dasar', 'easy', 'html-css'),
(227, 'Gambar latar belakang pada halaman', 'Background image styling untuk halaman', 1, 'Dasar', 'medium', 'html-css'),
(228, 'Daftar buku favorit', 'Book list dengan cover dan deskripsi', 1, 'Dasar', 'easy', 'html-css'),
(229, 'Halaman testimoni pelanggan', 'Customer testimonial dengan styling', 1, 'Dasar', 'medium', 'html-css'),
(230, 'Bagian artikel dengan gambar', 'Article section dengan image dan text', 1, 'Dasar', 'medium', 'html-css'),
(231, 'Menu navigasi horizontal', 'Horizontal navigation menu', 1, 'Dasar', 'medium', 'html-css'),
(232, 'Menu navigasi vertikal', 'Vertical sidebar navigation', 1, 'Dasar', 'medium', 'html-css'),
(233, 'Icon sosial media', 'Social media icons dengan styling', 1, 'Dasar', 'easy', 'html-css'),
(234, 'Halaman resep masakan', 'Recipe page dengan ingredients dan steps', 1, 'Dasar', 'medium', 'html-css'),
(235, 'Form feedback pengguna', 'User feedback form dengan rating', 1, 'Dasar', 'medium', 'html-css'),
(236, 'Halaman login statis', 'Static login page dengan styling', 1, 'Dasar', 'medium', 'html-css'),
(237, 'Gambar responsive', 'Responsive image dengan CSS', 1, 'Dasar', 'medium', 'html-css'),
(238, 'Form subscribe newsletter', 'Newsletter subscription form', 1, 'Dasar', 'medium', 'html-css'),
(239, 'Artikel dengan style font', 'Article dengan custom typography', 1, 'Dasar', 'medium', 'html-css'),
(240, 'Tampilan komentar pengguna', 'User comments display dengan styling', 1, 'Dasar', 'medium', 'html-css'),
(241, 'Desain border unik', 'Creative border designs dengan CSS', 1, 'Dasar', 'medium', 'html-css'),
(242, 'Teks marquee berjalan', 'Scrolling text dengan marquee effect', 1, 'Dasar', 'medium', 'html-css'),
(243, 'Link download file', 'Download links dengan styling khusus', 1, 'Dasar', 'easy', 'html-css'),
(244, 'Blockquote dengan style', 'Styled blockquote untuk kutipan', 1, 'Dasar', 'medium', 'html-css'),
(245, 'Gallery foto grid sederhana', 'Simple photo gallery dengan grid', 1, 'Dasar', 'medium', 'html-css'),
(246, 'Desain tombol disabled', 'Disabled button states dengan styling', 1, 'Dasar', 'medium', 'html-css'),
(247, 'Layout dengan section dan article', 'Semantic HTML layout dengan section/article', 1, 'Dasar', 'medium', 'html-css'),
(248, 'Card tim kerja', 'Team member cards dengan foto dan info', 1, 'Dasar', 'medium', 'html-css'),
(249, 'Halaman pengantar tugas', 'Task introduction page dengan styling', 1, 'Dasar', 'easy', 'html-css'),
(250, 'Halaman terima kasih', 'Thank you page dengan desain menarik', 1, 'Dasar', 'easy', 'html-css'),

-- Stage 2: Menengah (51-100)
(251, 'Card produk sederhana', 'Product card dengan image, title, dan price', 2, 'Menengah', 'medium', 'html-css'),
(252, 'Form login dengan validasi dasar', 'Login form dengan basic validation styling', 2, 'Menengah', 'medium', 'html-css'),
(253, 'Form registrasi pengguna', 'User registration form dengan multiple fields', 2, 'Menengah', 'medium', 'html-css'),
(254, 'Galeri gambar grid', 'Image gallery dengan CSS Grid layout', 2, 'Menengah', 'hard', 'html-css'),
(255, 'Layout blog post', 'Blog post layout dengan sidebar', 2, 'Menengah', 'hard', 'html-css'),
(256, 'Navigasi sticky saat scroll', 'Sticky navigation dengan CSS position', 2, 'Menengah', 'hard', 'html-css'),
(257, 'Header dan footer responsif', 'Responsive header dan footer design', 2, 'Menengah', 'hard', 'html-css'),
(258, 'Template undangan pernikahan', 'Wedding invitation template dengan styling elegant', 2, 'Menengah', 'hard', 'html-css'),
(259, 'Pricing table 3 kolom', 'Three-column pricing table dengan highlights', 2, 'Menengah', 'hard', 'html-css'),
(260, 'Responsive contact section', 'Contact section yang responsive', 2, 'Menengah', 'hard', 'html-css'),
(261, 'Portofolio kartu project', 'Portfolio project cards dengan hover effects', 2, 'Menengah', 'hard', 'html-css'),
(262, 'Website CV pribadi', 'Personal CV website dengan sections', 2, 'Menengah', 'hard', 'html-css'),
(263, 'Halaman event atau seminar', 'Event page dengan agenda dan registration', 2, 'Menengah', 'hard', 'html-css'),
(264, 'Profil perusahaan', 'Company profile page dengan about dan team', 2, 'Menengah', 'hard', 'html-css'),
(265, 'Laman katalog produk', 'Product catalog dengan grid dan filters', 2, 'Menengah', 'hard', 'html-css'),
(266, 'Struktur layout Grid CSS', 'Advanced CSS Grid layout structures', 2, 'Menengah', 'hard', 'html-css'),
(267, 'Layout landing page', 'Landing page layout dengan hero section', 2, 'Menengah', 'hard', 'html-css'),
(268, 'Halaman promosi diskon', 'Promotion page dengan discount highlights', 2, 'Menengah', 'medium', 'html-css'),
(269, 'Form pembayaran dummy', 'Payment form layout dengan styling', 2, 'Menengah', 'hard', 'html-css'),
(270, 'Countdown timer statis', 'Static countdown timer display', 2, 'Menengah', 'medium', 'html-css'),
(271, 'Layout FAQ dengan dropdown', 'FAQ layout dengan dropdown styling', 2, 'Menengah', 'hard', 'html-css'),
(272, 'Testimonial carousel statis', 'Static testimonial carousel layout', 2, 'Menengah', 'hard', 'html-css'),
(273, 'Navigasi dropdown sederhana', 'Simple dropdown navigation menu', 2, 'Menengah', 'hard', 'html-css'),
(274, 'Layout galeri foto per kategori', 'Categorized photo gallery layout', 2, 'Menengah', 'hard', 'html-css'),
(275, 'Halaman artikel berita', 'News article page dengan layout professional', 2, 'Menengah', 'hard', 'html-css'),
(276, 'Kartu tim dengan hover info', 'Team cards dengan hover information', 2, 'Menengah', 'hard', 'html-css'),
(277, 'Halaman fitur produk', 'Product features page dengan highlights', 2, 'Menengah', 'hard', 'html-css'),
(278, 'Hero section dengan CTA', 'Hero section dengan call-to-action buttons', 2, 'Menengah', 'hard', 'html-css'),
(279, 'Grid card harga', 'Pricing cards dalam grid layout', 2, 'Menengah', 'hard', 'html-css'),
(280, 'Halaman "coming soon"', 'Coming soon page dengan countdown', 2, 'Menengah', 'medium', 'html-css'),
(281, 'Halaman download aplikasi', 'App download page dengan app store links', 2, 'Menengah', 'medium', 'html-css'),
(282, 'Halaman login dark mode', 'Dark mode login page design', 2, 'Menengah', 'hard', 'html-css'),
(283, 'Footer dengan 4 kolom', 'Four-column footer layout', 2, 'Menengah', 'medium', 'html-css'),
(284, 'Form pencarian', 'Search form dengan styling advanced', 2, 'Menengah', 'medium', 'html-css'),
(285, 'Tombol share ke sosial media', 'Social media share buttons', 2, 'Menengah', 'medium', 'html-css'),
(286, 'Halaman maintenance', 'Under maintenance page design', 2, 'Menengah', 'medium', 'html-css'),
(287, 'Teks animasi loading', 'Loading text animation dengan CSS', 2, 'Menengah', 'hard', 'html-css'),
(288, 'Halaman registrasi dengan step', 'Multi-step registration page layout', 2, 'Menengah', 'hard', 'html-css'),
(289, 'Tabel responsif', 'Responsive table design', 2, 'Menengah', 'hard', 'html-css'),
(290, 'Formulir reservasi hotel', 'Hotel reservation form layout', 2, 'Menengah', 'hard', 'html-css'),
(291, 'Halaman "success" pembayaran', 'Payment success page design', 2, 'Menengah', 'medium', 'html-css'),
(292, 'Halaman lokasi Google Maps', 'Location page dengan maps placeholder', 2, 'Menengah', 'medium', 'html-css'),
(293, 'Notifikasi email sukses', 'Email success notification design', 2, 'Menengah', 'medium', 'html-css'),
(294, 'Box highlight', 'Highlight boxes untuk content penting', 2, 'Menengah', 'medium', 'html-css'),
(295, 'Desain header parallax', 'Parallax header effect dengan CSS', 2, 'Menengah', 'hard', 'html-css'),
(296, 'Animasi tombol saat klik', 'Button click animations dengan CSS', 2, 'Menengah', 'hard', 'html-css'),
(297, 'Desain loading bar', 'Loading bar progress indicator', 2, 'Menengah', 'medium', 'html-css'),
(298, 'Layout toko makanan', 'Food store layout dengan menu categories', 2, 'Menengah', 'hard', 'html-css'),
(299, 'Formulir subscribe newsletter', 'Advanced newsletter subscription form', 2, 'Menengah', 'medium', 'html-css'),
(300, 'Footer dengan langganan email', 'Footer dengan email subscription section', 2, 'Menengah', 'medium', 'html-css'),

-- Stage 3: Lanjutan (101-150)
(301, 'Halaman landing page lengkap', 'Complete landing page dengan multiple sections', 3, 'Lanjutan', 'hard', 'html-css'),
(302, 'Website portofolio multi-page', 'Multi-page portfolio website', 3, 'Lanjutan', 'hard', 'html-css'),
(303, 'Template e-learning', 'E-learning platform template', 3, 'Lanjutan', 'hard', 'html-css'),
(304, 'Desain toko online', 'E-commerce store design layout', 3, 'Lanjutan', 'hard', 'html-css'),
(305, 'UI login dengan animasi', 'Animated login interface', 3, 'Lanjutan', 'hard', 'html-css'),
(306, 'UI 404 page custom', 'Custom 404 error page dengan animasi', 3, 'Lanjutan', 'hard', 'html-css'),
(307, 'Website berita profesional', 'Professional news website layout', 3, 'Lanjutan', 'hard', 'html-css'),
(308, 'Web CV interaktif', 'Interactive CV website dengan animations', 3, 'Lanjutan', 'hard', 'html-css'),
(309, 'Dashboard statis', 'Static dashboard layout dengan widgets', 3, 'Lanjutan', 'hard', 'html-css'),
(310, 'Template admin panel', 'Admin panel template layout', 3, 'Lanjutan', 'hard', 'html-css'),
(311, 'Website hotel dengan galeri', 'Hotel website dengan image gallery', 3, 'Lanjutan', 'hard', 'html-css'),
(312, 'Web katalog produk fashion', 'Fashion product catalog website', 3, 'Lanjutan', 'hard', 'html-css'),
(313, 'UI form booking travel', 'Travel booking form interface', 3, 'Lanjutan', 'hard', 'html-css'),
(314, 'UI form pembayaran', 'Advanced payment form interface', 3, 'Lanjutan', 'hard', 'html-css'),
(315, 'Portofolio desain grafis', 'Graphic design portfolio showcase', 3, 'Lanjutan', 'hard', 'html-css'),
(316, 'UI produk makanan delivery', 'Food delivery product interface', 3, 'Lanjutan', 'hard', 'html-css'),
(317, 'Halaman checkout statis', 'Static checkout page layout', 3, 'Lanjutan', 'hard', 'html-css'),
(318, 'Halaman list produk filter', 'Product listing dengan filter options', 3, 'Lanjutan', 'hard', 'html-css'),
(319, 'UI kartu artikel hover', 'Article cards dengan hover effects', 3, 'Lanjutan', 'hard', 'html-css'),
(320, 'Website produk digital', 'Digital product website layout', 3, 'Lanjutan', 'hard', 'html-css'),
(321, 'Website komunitas', 'Community website dengan member sections', 3, 'Lanjutan', 'hard', 'html-css'),
(322, 'UI forum diskusi', 'Discussion forum interface layout', 3, 'Lanjutan', 'hard', 'html-css'),
(323, 'UI deskripsi produk', 'Product description page interface', 3, 'Lanjutan', 'hard', 'html-css'),
(324, 'Halaman donasi', 'Donation page dengan progress tracking', 3, 'Lanjutan', 'hard', 'html-css'),
(325, 'Halaman pendaftaran webinar', 'Webinar registration page layout', 3, 'Lanjutan', 'hard', 'html-css'),
(326, 'Website organisasi', 'Organization website dengan multiple pages', 3, 'Lanjutan', 'hard', 'html-css'),
(327, 'UI testimonial dinamis', 'Dynamic testimonial interface', 3, 'Lanjutan', 'hard', 'html-css'),
(328, 'UI FAQ interaktif', 'Interactive FAQ interface', 3, 'Lanjutan', 'hard', 'html-css'),
(329, 'UI menu makanan', 'Restaurant menu interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(330, 'UI blog minimalis', 'Minimalist blog interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(331, 'Form pemesanan tiket', 'Ticket booking form layout', 3, 'Lanjutan', 'hard', 'html-css'),
(332, 'Website landing undangan digital', 'Digital invitation landing website', 3, 'Lanjutan', 'hard', 'html-css'),
(333, 'UI galeri filter kategori', 'Gallery dengan category filters', 3, 'Lanjutan', 'hard', 'html-css'),
(334, 'UI artikel dengan ilustrasi', 'Article interface dengan illustrations', 3, 'Lanjutan', 'hard', 'html-css'),
(335, 'Halaman quiz statis', 'Static quiz page layout', 3, 'Lanjutan', 'hard', 'html-css'),
(336, 'Halaman survey pengguna', 'User survey page interface', 3, 'Lanjutan', 'hard', 'html-css'),
(337, 'UI kartu jadwal acara', 'Event schedule card interface', 3, 'Lanjutan', 'hard', 'html-css'),
(338, 'Website wedding organizer', 'Wedding organizer website layout', 3, 'Lanjutan', 'hard', 'html-css'),
(339, 'UI produk skincare', 'Skincare product interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(340, 'Landing page aplikasi mobile', 'Mobile app landing page', 3, 'Lanjutan', 'hard', 'html-css'),
(341, 'UI pemesanan kursi', 'Seat booking interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(342, 'Form registrasi seminar', 'Seminar registration form layout', 3, 'Lanjutan', 'hard', 'html-css'),
(343, 'UI kursus online', 'Online course interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(344, 'UI list agenda acara', 'Event agenda list interface', 3, 'Lanjutan', 'hard', 'html-css'),
(345, 'UI daftar anggota komunitas', 'Community member list interface', 3, 'Lanjutan', 'hard', 'html-css'),
(346, 'Landing page startup', 'Startup company landing page', 3, 'Lanjutan', 'hard', 'html-css'),
(347, 'Web pengingat tugas', 'Task reminder web interface', 3, 'Lanjutan', 'hard', 'html-css'),
(348, 'UI profil pengguna', 'User profile interface design', 3, 'Lanjutan', 'hard', 'html-css'),
(349, 'UI animasi teks scroll', 'Text scroll animation interface', 3, 'Lanjutan', 'hard', 'html-css'),
(350, 'Web penjualan digital download', 'Digital download sales website', 3, 'Lanjutan', 'hard', 'html-css'),

-- Stage 4: Mahir (151-200)
(351, 'Web agency full responsive', 'Full responsive agency website', 4, 'Mahir', 'hard', 'html-css'),
(352, 'UI event booking profesional', 'Professional event booking interface', 4, 'Mahir', 'hard', 'html-css'),
(353, 'Galeri foto masonry + filter', 'Masonry photo gallery dengan filters', 4, 'Mahir', 'hard', 'html-css'),
(354, 'Resume interaktif dengan animasi', 'Interactive animated resume', 4, 'Mahir', 'hard', 'html-css'),
(355, 'E-commerce frontpage modern', 'Modern e-commerce front page', 4, 'Mahir', 'hard', 'html-css'),
(356, 'UI blog dengan scroll animasi', 'Blog interface dengan scroll animations', 4, 'Mahir', 'hard', 'html-css'),
(357, 'Menu makanan restoran profesional', 'Professional restaurant menu design', 4, 'Mahir', 'hard', 'html-css'),
(358, 'Sistem navigasi multi page', 'Multi-page navigation system', 4, 'Mahir', 'hard', 'html-css'),
(359, 'UI travel booking page', 'Travel booking page interface', 4, 'Mahir', 'hard', 'html-css'),
(360, 'Responsive one-page wedding site', 'One-page responsive wedding website', 4, 'Mahir', 'hard', 'html-css'),
(361, 'Sistem desain (design system)', 'Complete design system components', 4, 'Mahir', 'hard', 'html-css'),
(362, 'UI layout SaaS product', 'SaaS product layout interface', 4, 'Mahir', 'hard', 'html-css'),
(363, 'Web edukasi responsif', 'Responsive education website', 4, 'Mahir', 'hard', 'html-css'),
(364, 'Web museum online', 'Online museum website layout', 4, 'Mahir', 'hard', 'html-css'),
(365, 'UI presentasi produk', 'Product presentation interface', 4, 'Mahir', 'hard', 'html-css'),
(366, 'UI galeri lightbox interaktif', 'Interactive lightbox gallery', 4, 'Mahir', 'hard', 'html-css'),
(367, 'UI dark mode switcher', 'Dark mode switcher interface', 4, 'Mahir', 'hard', 'html-css'),
(368, 'Layout dashboard interaktif', 'Interactive dashboard layout', 4, 'Mahir', 'hard', 'html-css'),
(369, 'UI billing & invoice', 'Billing and invoice interface', 4, 'Mahir', 'hard', 'html-css'),
(370, 'Halaman promo produk dengan timer', 'Product promo page dengan countdown timer', 4, 'Mahir', 'hard', 'html-css'),
(371, 'Template CV online dengan PDF download', 'Online CV template dengan PDF download', 4, 'Mahir', 'hard', 'html-css'),
(372, 'UI aplikasi keuangan pribadi', 'Personal finance app interface', 4, 'Mahir', 'hard', 'html-css'),
(373, 'UI laporan analitik', 'Analytics report interface', 4, 'Mahir', 'hard', 'html-css'),
(374, 'UI konfirmasi email & OTP', 'Email confirmation dan OTP interface', 4, 'Mahir', 'hard', 'html-css'),
(375, 'UI kartu promosi interaktif', 'Interactive promotion card interface', 4, 'Mahir', 'hard', 'html-css'),
(376, 'Halaman showcase produk digital', 'Digital product showcase page', 4, 'Mahir', 'hard', 'html-css'),
(377, 'Layout web travel agent', 'Travel agent website layout', 4, 'Mahir', 'hard', 'html-css'),
(378, 'Website e-learning kompleks', 'Complex e-learning website', 4, 'Mahir', 'hard', 'html-css'),
(379, 'Web UI pemesanan makanan mobile-first', 'Mobile-first food ordering interface', 4, 'Mahir', 'hard', 'html-css'),
(380, 'Web UI pemilihan seat', 'Seat selection web interface', 4, 'Mahir', 'hard', 'html-css'),
(381, 'Dashboard analisis penjualan', 'Sales analysis dashboard', 4, 'Mahir', 'hard', 'html-css'),
(382, 'Halaman detail produk dengan variasi', 'Product detail page dengan variations', 4, 'Mahir', 'hard', 'html-css'),
(383, 'UI drag & drop file upload', 'Drag and drop file upload interface', 4, 'Mahir', 'hard', 'html-css'),
(384, 'UI monitoring sistem', 'System monitoring interface', 4, 'Mahir', 'hard', 'html-css'),
(385, 'UI form multistep interaktif', 'Interactive multistep form interface', 4, 'Mahir', 'hard', 'html-css'),
(386, 'UI email template profesional', 'Professional email template interface', 4, 'Mahir', 'hard', 'html-css'),
(387, 'UI portofolio animator', 'Animator portfolio interface', 4, 'Mahir', 'hard', 'html-css'),
(388, 'Web UI builder layout', 'Layout builder web interface', 4, 'Mahir', 'hard', 'html-css'),
(389, 'UI review & rating produk', 'Product review and rating interface', 4, 'Mahir', 'hard', 'html-css'),
(390, 'Web sistem pemesanan hotel lengkap', 'Complete hotel booking system', 4, 'Mahir', 'hard', 'html-css'),
(391, 'Web real estat listing properti', 'Real estate property listing website', 4, 'Mahir', 'hard', 'html-css'),
(392, 'Web UI laporan keuangan tahunan', 'Annual financial report interface', 4, 'Mahir', 'hard', 'html-css'),
(393, 'Web UI edukasi anak-anak', 'Kids education web interface', 4, 'Mahir', 'hard', 'html-css'),
(394, 'Web tema festival', 'Festival themed website', 4, 'Mahir', 'hard', 'html-css'),
(395, 'UI pemesanan event musik', 'Music event booking interface', 4, 'Mahir', 'hard', 'html-css'),
(396, 'UI integrasi dengan Google Maps', 'Google Maps integration interface', 4, 'Mahir', 'hard', 'html-css'),
(397, 'UI form data dinamis', 'Dynamic data form interface', 4, 'Mahir', 'hard', 'html-css'),
(398, 'Web berita dengan infinite scroll', 'News website dengan infinite scroll', 4, 'Mahir', 'hard', 'html-css'),
(399, 'UI simulasi pinjaman', 'Loan simulation interface', 4, 'Mahir', 'hard', 'html-css'),
(400, 'UI admin sistem e-commerce', 'E-commerce admin system interface', 4, 'Mahir', 'hard', 'html-css');

-- Add all React projects (1-200) with new IDs starting from 401
INSERT INTO projects (id, title, description, stage, stage_name, difficulty, project_type) VALUES
-- Stage 1: Komponen, Props & State Dasar (1-50)
(401, 'Komponen "Hello World"', 'Membuat komponen React pertama dengan JSX', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(402, 'Komponen dengan props nama', 'Passing props untuk menampilkan nama dinamis', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(403, 'Komponen dengan gambar & teks', 'Komponen yang menampilkan gambar dan teks', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(404, 'Tombol klik counter', 'Counter sederhana dengan useState dan onClick', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(405, 'Kalkulator penjumlahan', 'Kalkulator sederhana untuk operasi penjumlahan', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(406, 'Form input nama', 'Form input dengan controlled component', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(407, 'Form input dan validasi', 'Form dengan validasi input sederhana', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(408, 'Komponen kartu produk', 'Card component untuk menampilkan produk', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(409, 'Komponen daftar makanan', 'List component untuk menampilkan menu makanan', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(410, 'Ubah warna latar (useState)', 'Toggle background color dengan state', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(411, 'Ganti tema dark/light', 'Theme switcher dengan useState', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(412, 'Tampilkan/Hide elemen (toggle)', 'Show/hide content dengan conditional rendering', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(413, 'Dropdown pilihan negara', 'Select dropdown untuk memilih negara', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(414, 'To-do list sederhana', 'Todo list dasar dengan add dan display', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(415, 'Komponen jam digital', 'Digital clock dengan useEffect dan setInterval', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(416, 'Komponen input angka + hasil total', 'Input multiple numbers dan tampilkan total', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(417, 'Komponen quote harian', 'Random quote generator dengan array', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(418, 'Komponen alert & notifikasi', 'Alert component dengan berbagai tipe', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(419, 'Form login sederhana', 'Login form dengan username dan password', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(420, 'Komponen bintang rating', 'Star rating component dengan onClick', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(421, 'Komponen badge/tag', 'Badge component dengan berbagai warna', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(422, 'Komponen profil user', 'User profile card dengan avatar dan info', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(423, 'Komponen tombol like', 'Like button dengan counter dan state', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(424, 'List map & render data array', 'Render array data dengan map function', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(425, 'Komponen galeri foto', 'Photo gallery dengan grid layout', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(426, 'Komponen navbar statis', 'Navigation bar component sederhana', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(427, 'Komponen footer', 'Footer component dengan links dan info', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(428, 'Komponen header dinamis', 'Header dengan props untuk title dan menu', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(429, 'Komponen halaman error', 'Error page component dengan pesan custom', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(430, 'Komponen pagination manual', 'Pagination component dengan state', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(431, 'Kalkulator BMI', 'BMI calculator dengan input berat dan tinggi', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(432, 'Checklist hobi', 'Checkbox list untuk memilih hobi', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(433, 'Komponen loading', 'Loading spinner component dengan state', 1, 'Komponen, Props & State Dasar', 'easy', 'react'),
(434, 'Komponen status online/offline', 'Status indicator dengan useEffect', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(435, 'Input banyak checkbox', 'Multiple checkbox dengan state array', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(436, 'Komponen progress bar', 'Progress bar dengan percentage props', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(437, 'Komponen FAQ (show/hide)', 'FAQ accordion dengan toggle state', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(438, 'Komponen jam analog', 'Analog clock dengan CSS dan useEffect', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(439, 'Komponen harga produk + diskon', 'Price component dengan perhitungan diskon', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(440, 'Komponen data kontak', 'Contact card dengan informasi lengkap', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(441, 'Counter like untuk setiap produk', 'Individual like counter untuk multiple items', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(442, 'Toggle bahasa ID/EN', 'Language switcher dengan conditional text', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(443, 'Komponen tab menu', 'Tab navigation dengan active state', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(444, 'Komponen step wizard (1-2-3)', 'Multi-step wizard dengan progress', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(445, 'Komponen kartu testimonial', 'Testimonial card dengan rating dan foto', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(446, 'Ganti gambar dengan button', 'Image switcher dengan button controls', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(447, 'Komponen input dengan karakter terbatas', 'Text input dengan character limit counter', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(448, 'Formulir subscribe', 'Newsletter subscription form', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),
(449, 'Komponen hasil polling', 'Poll results dengan bar chart sederhana', 1, 'Komponen, Props & State Dasar', 'hard', 'react'),
(450, 'Input tanggal dan waktu', 'Date time picker dengan state', 1, 'Komponen, Props & State Dasar', 'medium', 'react'),

-- Stage 2: State Lanjutan & Event Handling (51-100)
(451, 'Ubah warna dengan color picker', 'Color picker component dengan hex value', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(452, 'Komponen multi input form', 'Form dengan multiple input dan validation', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(453, 'Drag and drop item', 'Drag and drop functionality dengan event handlers', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(454, 'Komponen slider gambar', 'Image slider dengan navigation buttons', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(455, 'Accordion konten', 'Accordion component dengan multiple sections', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(456, 'Komponen komentar', 'Comment system dengan add dan display', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(457, 'Checklist tugas harian', 'Daily task checklist dengan localStorage', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(458, 'To-do list lengkap (CRUD state)', 'Full CRUD todo list dengan edit dan delete', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(459, 'Komponen form validasi email', 'Email validation dengan regex dan error messages', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(460, 'Komponen ubah tema dengan context', 'Theme context untuk global state management', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(461, 'Komponen kalkulator kalkulasi', 'Advanced calculator dengan multiple operations', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(462, 'Filter daftar produk', 'Product filter dengan search dan category', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(463, 'Komponen select dinamis', 'Dynamic select dengan dependent options', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(464, 'Komponen search bar', 'Search bar dengan real-time filtering', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(465, 'Komponen alert otomatis (timeout)', 'Auto-dismiss alert dengan setTimeout', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(466, 'Komponen notifikasi dinamis', 'Dynamic notification system dengan queue', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(467, 'Komponen input range slider', 'Range slider dengan min/max values', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(468, 'Komponen hitung mundur', 'Countdown timer dengan useEffect', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(469, 'Komponen waktu sholat (manual)', 'Prayer time display dengan static data', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(470, 'Komponen card artikel blog', 'Blog article card dengan excerpt dan tags', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(471, 'Komponen multi step form', 'Multi-step form dengan validation per step', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(472, 'Komponen harga dinamis', 'Dynamic pricing dengan quantity dan discount', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(473, 'Simulasi voting', 'Voting system dengan real-time results', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(474, 'Komponen checklist belanja', 'Shopping checklist dengan categories', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(475, 'UI pemesanan makanan', 'Food ordering interface dengan cart', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(476, 'Komponen upload file', 'File upload dengan preview dan validation', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(477, 'Komponen upload gambar preview', 'Image upload dengan preview thumbnail', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(478, 'UI kartu user dinamis', 'Dynamic user card dengan editable fields', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(479, 'Komponen text area komentar', 'Comment textarea dengan character count', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(480, 'Komponen status kirim form', 'Form submission status dengan loading states', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(481, 'Komponen toggle animasi', 'Animated toggle dengan CSS transitions', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(482, 'Simpan nilai form ke localStorage', 'Form persistence dengan localStorage', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(483, 'Komponen rating bintang interaktif', 'Interactive star rating dengan hover effects', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(484, 'Komponen ekspansi teks panjang', 'Expandable text dengan read more/less', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(485, 'Validasi password (kuat/lemah)', 'Password strength validator dengan indicators', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(486, 'Input ganda dalam satu form', 'Complex form dengan nested input groups', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(487, 'UI pemesanan kursi', 'Seat booking interface dengan selection', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(488, 'UI reservasi jadwal', 'Schedule reservation dengan time slots', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(489, 'Komponen kalkulasi gaji', 'Salary calculator dengan allowances', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(490, 'Komponen penilaian ujian', 'Exam scoring system dengan grading', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(491, 'UI penilaian lomba', 'Competition scoring interface', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(492, 'Komponen pemilih waktu', 'Time picker dengan hour/minute selection', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(493, 'Komponen avatar dengan inisial', 'Avatar component dengan auto-generated initials', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(494, 'Input tag dinamis', 'Dynamic tag input dengan add/remove', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(495, 'UI sistem absensi', 'Attendance system dengan check-in/out', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(496, 'UI daftar tugas kelompok', 'Group task management interface', 2, 'State Lanjutan & Event Handling', 'hard', 'react'),
(497, 'UI input voucher', 'Voucher code input dengan validation', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(498, 'Komponen konversi suhu', 'Temperature converter dengan multiple units', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(499, 'Komponen waktu real-time', 'Real-time clock dengan timezone support', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),
(500, 'Komponen cuaca dummy (tanpa API)', 'Weather display dengan static data', 2, 'State Lanjutan & Event Handling', 'medium', 'react'),

-- Stage 3: Routing, Hooks & API (101-150)
(501, 'Website multi-halaman dengan React Router', 'Multi-page website dengan React Router setup', 3, 'Routing, Hooks & API', 'hard', 'react'),
(502, 'Komponen halaman "Beranda", "Tentang", "Kontak"', 'Basic pages dengan routing navigation', 3, 'Routing, Hooks & API', 'medium', 'react'),
(503, 'Navigasi antar halaman (Link)', 'Navigation dengan React Router Link', 3, 'Routing, Hooks & API', 'medium', 'react'),
(504, 'Layout website dengan children props', 'Layout component dengan nested routing', 3, 'Routing, Hooks & API', 'hard', 'react'),
(505, 'Komponen layout header/footer tetap', 'Persistent layout dengan Outlet', 3, 'Routing, Hooks & API', 'medium', 'react'),
(506, 'Halaman login dan dashboard', 'Login page dengan protected dashboard', 3, 'Routing, Hooks & API', 'hard', 'react'),
(507, 'Navigasi dengan parameter (URL param)', 'Dynamic routing dengan useParams', 3, 'Routing, Hooks & API', 'hard', 'react'),
(508, 'Halaman produk berdasarkan ID', 'Product detail page dengan URL parameters', 3, 'Routing, Hooks & API', 'hard', 'react'),
(509, 'Komponen loading saat routing', 'Loading states untuk route transitions', 3, 'Routing, Hooks & API', 'medium', 'react'),
(510, 'Komponen protected route', 'Route protection dengan authentication', 3, 'Routing, Hooks & API', 'hard', 'react'),
(511, 'Komponen redirect otomatis', 'Automatic redirects dengan useNavigate', 3, 'Routing, Hooks & API', 'medium', 'react'),
(512, 'Ambil data dari API publik (fetch)', 'Basic API fetching dengan useEffect', 3, 'Routing, Hooks & API', 'medium', 'react'),
(513, 'Tampilkan data film dari API', 'Movie data display dari public API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(514, 'Tampilkan data cuaca dari API', 'Weather data integration dengan API', 3, 'Routing, Hooks & API', 'hard', 'react'),
(515, 'Komponen pencarian data API', 'Search functionality dengan API calls', 3, 'Routing, Hooks & API', 'hard', 'react'),
(516, 'Komponen pagination dari API', 'API pagination dengan page navigation', 3, 'Routing, Hooks & API', 'hard', 'react'),
(517, 'Fetch data user (dummy JSONPlaceholder)', 'User data dari JSONPlaceholder API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(518, 'Fetch data buku', 'Book data integration dengan API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(519, 'Komponen daftar posting blog', 'Blog posts list dari API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(520, 'Komponen komentar API', 'Comments system dengan API integration', 3, 'Routing, Hooks & API', 'hard', 'react'),
(521, 'Update data dengan fetch PUT', 'Data update dengan PUT requests', 3, 'Routing, Hooks & API', 'hard', 'react'),
(522, 'Hapus data (DELETE)', 'Data deletion dengan DELETE requests', 3, 'Routing, Hooks & API', 'hard', 'react'),
(523, 'Tambah data ke API (POST)', 'Data creation dengan POST requests', 3, 'Routing, Hooks & API', 'hard', 'react'),
(524, 'Login dengan token dummy', 'Authentication dengan token simulation', 3, 'Routing, Hooks & API', 'hard', 'react'),
(525, 'Simpan token di localStorage', 'Token persistence dengan localStorage', 3, 'Routing, Hooks & API', 'medium', 'react'),
(526, 'Kirim data form ke API', 'Form submission ke API endpoint', 3, 'Routing, Hooks & API', 'hard', 'react'),
(527, 'Komponen filter API berdasarkan kategori', 'API filtering dengan query parameters', 3, 'Routing, Hooks & API', 'hard', 'react'),
(528, 'Tampilkan error API', 'Error handling untuk API calls', 3, 'Routing, Hooks & API', 'medium', 'react'),
(529, 'Loading state saat fetch', 'Loading indicators untuk API requests', 3, 'Routing, Hooks & API', 'medium', 'react'),
(530, 'Fetch data dengan useEffect', 'Data fetching dengan useEffect patterns', 3, 'Routing, Hooks & API', 'medium', 'react'),
(531, 'Buat custom hook fetch', 'Custom hook untuk API operations', 3, 'Routing, Hooks & API', 'hard', 'react'),
(532, 'Tampilkan status online API', 'API status monitoring component', 3, 'Routing, Hooks & API', 'medium', 'react'),
(533, 'Komponen news dari API', 'News feed dari news API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(534, 'Komponen daftar pengguna dari API', 'User list dengan API integration', 3, 'Routing, Hooks & API', 'medium', 'react'),
(535, 'Komponen pendaftaran event API', 'Event registration dengan API', 3, 'Routing, Hooks & API', 'hard', 'react'),
(536, 'Komponen form CRUD dengan fetch', 'Full CRUD operations dengan API', 3, 'Routing, Hooks & API', 'hard', 'react'),
(537, 'Integrasi dengan Airtable', 'Airtable API integration', 3, 'Routing, Hooks & API', 'hard', 'react'),
(538, 'Integrasi dengan mock API', 'Mock API service integration', 3, 'Routing, Hooks & API', 'medium', 'react'),
(539, 'Fetch data bank Indonesia', 'Indonesian bank data dari API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(540, 'Tampilkan nilai tukar uang', 'Currency exchange rates dari API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(541, 'Komponen event handler API', 'Advanced API event handling', 3, 'Routing, Hooks & API', 'hard', 'react'),
(542, 'Integrasi dengan endpoint REST', 'RESTful API integration patterns', 3, 'Routing, Hooks & API', 'hard', 'react'),
(543, 'UI katalog produk dari API', 'Product catalog dengan API data', 3, 'Routing, Hooks & API', 'hard', 'react'),
(544, 'Detail produk dinamis', 'Dynamic product details dari API', 3, 'Routing, Hooks & API', 'hard', 'react'),
(545, 'API pemesanan makanan', 'Food ordering dengan API backend', 3, 'Routing, Hooks & API', 'hard', 'react'),
(546, 'Web jadwal sholat (API lokal)', 'Prayer schedule dengan local API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(547, 'Tampilkan lokasi dari API', 'Location data dari geolocation API', 3, 'Routing, Hooks & API', 'medium', 'react'),
(548, 'Filter berita berdasarkan tanggal', 'News filtering dengan date parameters', 3, 'Routing, Hooks & API', 'hard', 'react'),
(549, 'UI status pesanan dari API', 'Order status tracking dengan API', 3, 'Routing, Hooks & API', 'hard', 'react'),
(550, 'Sistem login simulasi JWT (tanpa backend)', 'JWT simulation untuk authentication', 3, 'Routing, Hooks & API', 'hard', 'react'),

-- Stage 4: Mini Project & Layout UI (151-200)
(551, 'Aplikasi to-do list', 'Full-featured todo list application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(552, 'Aplikasi kalkulator', 'Scientific calculator application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(553, 'Aplikasi konversi suhu', 'Temperature conversion utility', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(554, 'Aplikasi pemesanan makanan', 'Food ordering application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(555, 'Aplikasi daftar film', 'Movie database application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(556, 'Aplikasi pendaftaran seminar', 'Seminar registration system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(557, 'Aplikasi voting', 'Voting system application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(558, 'Aplikasi quiz', 'Interactive quiz application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(559, 'Aplikasi rating', 'Rating and review system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(560, 'Aplikasi booking hotel', 'Hotel reservation system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(561, 'Aplikasi rental motor', 'Motorcycle rental application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(562, 'Aplikasi toko baju', 'Clothing store application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(563, 'Aplikasi toko bunga', 'Flower shop application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(564, 'Aplikasi prediksi cuaca', 'Weather forecast application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(565, 'Aplikasi pendaftaran lomba', 'Competition registration system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(566, 'Aplikasi galeri foto', 'Photo gallery application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(567, 'Aplikasi kurs rupiah', 'Currency exchange application', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(568, 'Aplikasi kontak sederhana', 'Simple contact management', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(569, 'Aplikasi manajemen tugas', 'Task management system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(570, 'Aplikasi absensi kelas', 'Classroom attendance system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(571, 'Aplikasi jurnal harian', 'Daily journal application', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(572, 'Aplikasi blog post', 'Blog posting platform', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(573, 'Aplikasi e-learning', 'E-learning platform', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(574, 'Aplikasi data alumni', 'Alumni database system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(575, 'Aplikasi form multi step', 'Multi-step form application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(576, 'Aplikasi pemesanan tiket', 'Ticket booking system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(577, 'Aplikasi voting pemilu', 'Election voting system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(578, 'Aplikasi rating film', 'Movie rating platform', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(579, 'Aplikasi kartu kredit', 'Credit card management', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(580, 'Aplikasi kartu alumni', 'Alumni card system', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(581, 'Aplikasi daftar harga', 'Price list management', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(582, 'Aplikasi jadwal pelajaran', 'Class schedule system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(583, 'Aplikasi manajemen project', 'Project management tool', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(584, 'Aplikasi konsultasi online', 'Online consultation platform', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(585, 'Aplikasi data mahasiswa', 'Student data management', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(586, 'Aplikasi toko sepatu', 'Shoe store application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(587, 'Aplikasi sertifikat digital', 'Digital certificate system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(588, 'Aplikasi lirik lagu', 'Song lyrics database', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(589, 'Aplikasi penilaian lomba', 'Competition scoring system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(590, 'Aplikasi penjadwalan kuliah', 'University scheduling system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(591, 'Aplikasi leaderboard', 'Leaderboard ranking system', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(592, 'Aplikasi toko alat tulis', 'Stationery store application', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(593, 'Aplikasi data pegawai', 'Employee data management', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(594, 'Aplikasi dashboard admin', 'Admin dashboard interface', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(595, 'Aplikasi web portofolio', 'Portfolio website builder', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(596, 'Aplikasi kas sederhana', 'Simple cash management', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(597, 'Aplikasi konversi mata uang', 'Currency converter application', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(598, 'Aplikasi web event', 'Event management platform', 4, 'Mini Project & Layout UI', 'hard', 'react'),
(599, 'Aplikasi catatan belanja', 'Shopping notes application', 4, 'Mini Project & Layout UI', 'medium', 'react'),
(600, 'Aplikasi reservasi kursi', 'Seat reservation system', 4, 'Mini Project & Layout UI', 'hard', 'react');